### ISSUE TITLE
Final 0.1 checklist

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJFlux.jl#41]
- [x] extra n_channels arg PR #39 

- [x] change name of method for building chain?  #40

- [x] switch to Zygote #19

- [x] check the tutorial at https://github.com/alan-turing-institute/DataScienceTutorials.jl/pull/55 works locally

- [x] Register!!  PR pending: https://github.com/JuliaRegistries/General/pull/16542

- [x] register package with MLJ model registry

**Comment by ayush-1506** [comment]
@ablaom Regarding switching to Zygote, I found a discrepancy here: https://github.com/FluxML/Flux.jl/issues/1084 . Apparently now Dropout doesn't naturally turn things off unless it is in the _training mode_ (which has a slightly different definition that tracker-flux training mode).
 I believe they've added it to the v0.11 milestone for Flux. We could use Zygote-Flux (but remove the dropout test, since it fails) or live with tracker for the moment. What do you think?

**Comment by ablaom** [comment]
@ayush-1506 Thanks for investigating. Appreciate it!

Possibly I'm missing something, but my reading of FluxML/Flux.jl#1084 is that the post-zygote implementation of dropout is flawed  in a rather specific way but works fine in "normal" usage, no? After all, it would be kinda shocking if dropout has been fundamentally flawed since that issue opened three months ago. Perhaps you could make further enquiries? 

Perhaps @AzamatB or @jondeuce could comment?

It would also help my understanding to see exactly what tests are failing. Are you able to update #19? Also, looking at the tests I see that we while we check whether or not a chain's  is in test or train mode at various points, we don't actually test if using dropout makes any difference to training outcomes.  That is, there should be a test where we run `Short()` (say) with and without dropout *using the same initial values for weights*  and check the training outcomes are genuinely different. Such a test would be especially important given the existence of dropout issues.

**Comment by ayush-1506** [comment]
@ablaom If you look at the dropout test i.e:
```
@testset "dropout" begin
    model = MLJFlux.Short()
    chain = MLJFlux.build(model, 5, 1)

    input = rand(5,1)
    # At the moment, Dropout is active:
    @test chain(input) != chain(input)
```

Since we are not in _train mode_ (post zygote era) right now, the test fails (we always get the same result of `chain(input)`)

**Comment by ayush-1506** [comment]
I've opened #43 that should make things more apparent.

**Comment by AzamatB** [comment]
Regarding [Flux.jl#1084](https://github.com/FluxML/Flux.jl/issues/1084), there is a `Dropout` layer, which is turned on/off by `trainmode!/testmode!` and `dropout` function, which should always perform dropout independently of `trainmode!/testmode!` flag, but with the current implementation it does depend on it.

**Comment by ablaom** [comment]
Yes, so if I specify one or more `Dropout` layers I can still turn them on and off (simultaneously) with the flag setters and it will work as expected, yes? 

Indeed, even if I don't set them, the :auto default ought to make them work with the standard training=on test=off behaviour, yes? 

If I am not using the `dropout` function, to get "special" behaviour, then there isn't really an issue, yes?

**Comment by jondeuce** [comment]
@ablaom My recollection of the issue is that Dropout layers work as intended in normal usage (i.e. the :auto default). The problem, however, is that when one explicitly sets trainmode!(layer), the docs imply that layer(x) should apply dropout to x both inside and outside gradient calls. But this does not happen, because while this does make Dropout layers call the dropout function internally, the dropout function itself is identity outside of gradient calls, and therefore no dropout is applied even though trainmode!(layer) was specified.

Defining the lower level dropout function to apply dropout regardless of whether it is inside or outside a gradient call would fix this issue, and it seems more natural to me (also, I believe it is stated in the docs that this should be the case).

**Comment by ablaom** [comment]
@jondeuce @AzamatB Many thanks for these clarifications!

**Comment by azev77** [comment]
@ablaom it looks like MLJFlux is registered, is the checklist now complete?
